---
title: "Homework 1"
author: "Charandeep Grewal 301190855, James Hopkins 301139318, Alisha McGrath 301242597"
date: "September 12, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Question 1 (Chapter 2, #1, 8 marks)

(a) <your answer here>

(b) <etc.>

(c)

(d)


## Question 2 (Chapter 2, #2, 6 marks)

(a) 
   Regression, Inference, n = 500, p = 4
(b)
   Classification, Prediction, n = 20, p = 13
(c)
   Regression, Prediction, n = 52, p =3

```{r}
library(ISLR)
data(Auto)
head(Auto)
```

9b)
```{r}
sapply(Auto[, (1:7)], range)
```

9c) 
```{r}
sapply(Auto[, (1:7)], mean)
sapply(Auto[, (1:7)], sd)
```

9d)
```{r}
Auto1 <- Auto[-10:-85, (1:7)]
sapply(Auto1[, (1:7)], range)
sapply(Auto[, (1:7)], mean)
sapply(Auto[, (1:7)], sd)
```

9e)
```{r}
library(ggplot2)
plot(Auto$cylinders, Auto$mpg,xlab="Cylinders",ylab="Mpg")
plot(Auto$weight, Auto$mpg,xlab="Weight",ylab="Mpg")
plot(Auto$horsepower, Auto$mpg,xlab="Horsepower",ylab="Mpg")
plot(Auto$year, Auto$mpg,xlab="Year",ylab="Mpg")
plot(Auto$acceleration, Auto$mpg,xlab="Acceleration",ylab="Mpg")
plot(Auto$displacement, Auto$mpg,xlab="Displacement",ylab="Mpg")
```